
SUBROUTINE readinvals
     ! This currently reads in the values from fort.7 in fortran. From the fort.7, it currently reads in the name blocks:
     !               COMMENT, INPPL, INVARPARAM, INMAG, INBINVAL, INSIMPRAD, INCLOUDY
     !    all the others were not working, but may be updated in the future
     !    the other name blocks are commented out, but if you add them in the future you have to
     !             declare the variable types
       CHARACTER(30) :: AEROSOLMODEL, AEROSOLCOMP, HAZETYPE
   
       REAL MTLX, METALLICITY, MOLEF(13), AERTOTTAU, CLOUDTOP, AERHFRAC, PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,ASYMLW, SIG_AREA
       REAL PHI_LON,GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
       REAL RFCOEFF_IN,BOTRELAXTIME,FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
       REAL BFIELD,TDRAG_MIN,RAMPUP,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2
       REAL SURFEMIS,RAYSCATLAM(3),ABSSW,ABSLW,ALBSW,OOM_IN,AERLAYERS,CLOUDBASE
   
       INTEGER NLPLOTMAP_IN,NTSTEP_IN,NSKIP_IN
       INTEGER STTEMP1,STTEMP2,NLCR,NCUTOP,JSKIPLON,JSKIPLAT,NEWTB,NEWTE,with_TiO_and_VO
   
       LOGICAL DELTASCALE, HAZES, PICKET_FENCE_CLOUDS
       LOGICAL LPLOTMAP,LBDRAG,LBIN
       LOGICAL LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR
       LOGICAL DOSWRAD,DOLWRAD,LWSCAT,FLXLIMDIF,RAYSCAT,AEROSOLS,picket_fence_optical_depths
   
       NAMELIST/INPPL/GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
       NAMELIST/INVARPARAM/OOM_IN,LPLOTMAP,NLPLOTMAP_IN,RFCOEFF_IN,NTSTEP_IN,NSKIP_IN,BOTRELAXTIME,&
            FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
       NAMELIST/INMAG/LBDRAG,BFIELD,TDRAG_MIN,RAMPUP
       NAMELIST/INBINVAL/LBIN,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,STTEMP1,STTEMP2
       NAMELIST/INPHYS/LBL,LBD,LCR,LLR,LRD,LCUBM,LCBADJ,CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKTC,AKQC,NLCR,&
            NCUTOP,FW,FRADC,CURHM,CUBMT,CBADJT,CBADJP,LSL,LOC,LNOICE,LOLDBL,LCOND,LNNSK,ITSLL,ITSLO
       NAMELIST/INPRSIJ/TFRC,RESTIM,RESTTT,REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN
       NAMELIST/INSIMPRAD/LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,JSKIPLON,JSKIPLAT,DOSWRAD,DOLWRAD,&
            LWSCAT,FLXLIMDIF,SURFEMIS,RAYSCAT,RAYSCATLAM,AEROSOLS,ABSSW,ABSLW,ALBSW,NEWTB,NEWTE,&
            with_TiO_and_VO,picket_fence_optical_depths
       NAMELIST/INCLOUDY/AEROSOLMODEL,AEROSOLCOMP,MTLX,METALLICITY,HAZES,PICKET_FENCE_CLOUDS,&
            MOLEF,AERLAYERS,AERTOTTAU,CLOUDBASE,CLOUDTOP,AERHFRAC,PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,&
            ASYMLW,DELTASCALE,SIG_AREA,PHI_LON,HAZETYPE
       

       COMMON/CLOUDY/AEROSOLMODEL,AEROSOLCOMP,MTLX,METALLICITY,HAZES,PICKET_FENCE_CLOUDS,&
            MOLEF,AERLAYERS,AERTOTTAU,CLOUDBASE,CLOUDTOP,AERHFRAC,PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,&
            ASYMLW,DELTASCALE,SIG_AREA,PHI_LON,HAZETYPE
       COMMON/PPL/GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
       COMMON/VARPARAM/OOM_IN,LPLOTMAP,NLPLOTMAP_IN,RFCOEFF_IN,NTSTEP_IN,NSKIP_IN,BOTRELAXTIME,&
            FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
       COMMON/MAG/LBDRAG,BFIELD,TDRAG_MIN,RAMPUP
       COMMON/BINVAL/LBIN,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,STTEMP1,STTEMP2
       COMMON/SIMPRAD/LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,JSKIPLON,JSKIPLAT,DOSWRAD,DOLWRAD,LWSCAT,&
            FLXLIMDIF,SURFEMIS,RAYSCAT,RAYSCATLAM,AEROSOLS,ABSSW,ABSLW,ALBSW,&
            NEWTB,NEWTE,with_TiO_and_VO,picket_fence_optical_depths
       write(*,*) 'ass'
       READ(7,INPPL)
       READ(7,INVARPARAM)
       READ(7,INMAG)
       READ(7,INBINVAL)
       READ(7,INSIMPRAD)
       READ(7,INCLOUDY)
   
   END SUBROUTINE readinvals
   
   
   