
SUBROUTINE readinvals
  ! This currently reads in the values from fort.7 in fortran. From the fort.7, it currently reads in the name blocks:
  !               COMMENT, INPPL, INVARPARAM, INMAG, INBINVAL, INSIMPRAD, INCLOUDY
  !    all the others were not working, but may be updated in the future
  !    the other name blocks are commented out, but if you add them in the future you have to
  !             declare the variable types
    CHARACTER(30) :: AEROSOLMODEL, AEROSOLCOMP, HAZETYPE
    CHARACTER(50) :: THECOMMENT

    REAL MTLX, METALLICITY, MOLEF(13), AERTOTTAU, CLOUDTOP, AERHFRAC, PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,ASYMLW, SIG_AREA
    REAL PHI_LON,GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
    REAL RFCOEFF_IN,BOTRELAXTIME,FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
    REAL BFIELD,TDRAG_MIN,RAMPUP,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2
    REAL SURFEMIS,RAYSCATLAM(3),ABSSW,ABSLW,ALBSW

    INTEGER AERLAYERS, CLOUDBASE,OOM_IN,NLPLOTMAP_IN,NTSTEP_IN,NSKIP_IN
    INTEGER STTEMP1,STTEMP2,NLCR,NCUTOP,JSKIPLON,JSKIPLAT,NEWTB,NEWTE,with_TiO_and_VO

    LOGICAL DELTASCALE, HAZES, PICKET_FENCE_CLOUDS
    LOGICAL LPLOTMAP,LBDRAG,LBIN
    LOGICAL LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR
    LOGICAL DOSWRAD,DOLWRAD,LWSCAT,FLXLIMDIF,RAYSCAT,AEROSOLS,picket_fence_optical_depths

    NAMELIST/COMMENT/THECOMMENT
    NAMELIST/INPPL/GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
    !NAMELIST/INPRN/KRUN,BEGDAY,TSPD,KITS,PNU,TDISS,LFLUX,BEGDOY,NDEL,T0,LRSTRT,LSTRETCH,LSHORT,LTVEC,LBALAN,LRESTIJ,LCLIM,LPERPET,&
    !     L22L,LOROG,LCSFCT,KOLOUR,LNOISE,LMASCOR,LMASOLD,LMASPRT
    !weird value in this namelist so currently ignoring it
    !NAMELIST/INPOP/RNTAPE,KOUNTH,KOUNTR,KOUNTP,KOUNTE,NCOEFF,NLAT,LGPO,LSPO,RNTAPO,NTRACO,LSHIST,LMINIH
    NAMELIST/INVARPARAM/OOM_IN,LPLOTMAP,NLPLOTMAP_IN,RFCOEFF_IN,NTSTEP_IN,NSKIP_IN,BOTRELAXTIME,&
         FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
    NAMELIST/INMAG/LBDRAG,BFIELD,TDRAG_MIN,RAMPUP
    NAMELIST/INBINVAL/LBIN,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,STTEMP1,STTEMP2
    NAMELIST/INPHYS/LBL,LBD,LCR,LLR,LRD,LCUBM,LCBADJ,CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKTC,AKQC,NLCR,&
         NCUTOP,FW,FRADC,CURHM,CUBMT,CBADJT,CBADJP,LSL,LOC,LNOICE,LOLDBL,LCOND,LNNSK,ITSLL,ITSLO
    NAMELIST/INPRSIJ/TFRC,RESTIM,RESTTT,REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN
    NAMELIST/INSIMPRAD/LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,JSKIPLON,JSKIPLAT,DOSWRAD,DOLWRAD,&
         LWSCAT,FLXLIMDIF,SURFEMIS,RAYSCAT,RAYSCATLAM,AEROSOLS,ABSSW,ABSLW,ALBSW,NEWTB,NEWTE,&
         with_TiO_and_VO,picket_fence_optical_depths
    NAMELIST/INCLOUDY/AEROSOLMODEL,AEROSOLCOMP,MTLX,METALLICITY,HAZES,PICKET_FENCE_CLOUDS,&
         MOLEF,AERLAYERS,AERTOTTAU,CLOUDBASE,CLOUDTOP,AERHFRAC,PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,&
         ASYMLW,DELTASCALE,SIG_AREA,PHI_LON,HAZETYPE
    !NAMELIST/INQ/LRH,RH,LNSURF


    
    COMMON/CLOUDY/AEROSOLMODEL,AEROSOLCOMP,MTLX,METALLICITY,HAZES,PICKET_FENCE_CLOUDS,&
         MOLEF,AERLAYERS,AERTOTTAU,CLOUDBASE,CLOUDTOP,AERHFRAC,PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,&
         ASYMLW,DELTASCALE,SIG_AREA,PHI_LON,HAZETYPE
    COMMON/COMMEN/THECOMMENT
    COMMON/PPL/GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
    !COMMON/PRN/KRUN,BEGDAY,TSPD,KITS,PNU,TDISS,LFLUX,BEGDOY,NDEL,T0,LRSTRT,LSTRETCH,LSHORT,LTVEC,&
 !        LBALAN,LRESTIJ,LCLIM,LPERPET,L22L,LOROG,LCSFCT,KOLOUR,LNOISE,LMASCOR,LMASOLD,LMASPRT
!    COMMON/POP/RNTAPE,KOUNTH,KOUNTR,KOUNTP,KOUNTE,NCOEFF,NLAT,LGPO,LSPO,RNTAPO,NTRACO,LSHIST,LMINIH
    COMMON/VARPARAM/OOM_IN,LPLOTMAP,NLPLOTMAP_IN,RFCOEFF_IN,NTSTEP_IN,NSKIP_IN,BOTRELAXTIME,&
         FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
    COMMON/MAG/LBDRAG,BFIELD,TDRAG_MIN,RAMPUP
    COMMON/BINVAL/LBIN,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,STTEMP1,STTEMP2
   ! COMMON/PHYS/LBL,LBD,LCR,LLR,LRD,LCUBM,LCBADJ,CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKTC,AKQC,NLCR,NCUTOP,&
   !      FW,FRADC,CURHM,CUBMT,CBADJT,CBADJP,LSL,LOC,LNOICE,LOLDBL,LCOND,LNNSK,ITSLL,ITSLO
  !  COMMON/PRSIJ/TFRC,RESTIM,RESTTT,REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN
    COMMON/SIMPRAD/LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,JSKIPLON,JSKIPLAT,DOSWRAD,DOLWRAD,LWSCAT,&
         FLXLIMDIF,SURFEMIS,RAYSCAT,RAYSCATLAM,AEROSOLS,ABSSW,ABSLW,ALBSW,&
         NEWTB,NEWTE,with_TiO_and_VO,picket_fence_optical_depths
   ! COMMON/INQC/LRH,RH,LNSURF

    READ(7,COMMENT)
    READ(7,INPPL)
    !READ(7,INPRN)
   ! READ(7,INPOP)
    READ(7,INVARPARAM)
    READ(7,INMAG)
    READ(7,INBINVAL)
   ! READ(7,INPHYS)
   ! READ(7,INPRSIJ)
    READ(7,INSIMPRAD)
    READ(7,INCLOUDY)
    !READ(7,INQ)


END SUBROUTINE readinvals


