! intent of this is to read in the fort.7 file and grab all values, then export to a python readable dictionary

SUBROUTINE testing1(a)
    implicit none
    INTEGER, intent(in) :: a
    !REAL, intent(out) :: realarray(100)
    REAL, intent(out) :: TESTSTRING(79)
    CHARACTER(30) :: AEROSOLMODEL, AEROSOLCOMP, HAZETYPE
    CHARACTER(50) :: THECOMMENT

    REAL MTLX, METALLICITY, MOLEF(13), AERTOTTAU, CLOUDTOP, AERHFRAC, PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,ASYMLW, SIG_AREA, PHI_LON,GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT,KRUN,BEGDAY,TSPD,PNU,TDISS,BEGDOY
    REAL RFCOEFF_IN,BOTRELAXTIME,FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN,BFIELD,TDRAG_MIN,RAMPUP,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2
    REAL CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKQC,FW,FRADC,CURHM,CUBMT,CBADJT,TFRC,RESTIM, RESTTT(50),REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN,SURFEMIS,RAYSCATLAM(3),ABSSW,ABSLW,ALBSW,RH

    INTEGER AERLAYERS, CLOUDBASE,KITS,NDEL,T0,KOLOUR,OOM_IN,NLPLOTMAP_IN,NTSTEP_IN,NSKIP_IN,STTEMP1,STTEMP2,NLCR,NCUTOP,ITSLL,ITSLO,JSKIPLON,JSKIPLAT,NEWTB,NEWTE,with_TiO_and_VO
    LOGICAL DELTASCALE, HAZES, PICKET_FENCE_CLOUDS,LFLUX,LRSTRT,LSTRETCH,LSHORT,LTVEC,LBALAN,LRESTIJ,LCLIM,LPERPET,L22L,LOROG,LCSFCT,LNOISE,LMASCOR,LMASOLD,LMASPRT,LPLOTMAP,LBDRAG,LBIN,LBL,LBD,LCR,LLR,LRD,LCUBM,LCBADJ
    LOGICAL LSL,LOC,LNOICE,LOLDBL,LCOND,LNNSK,LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,DOSWRAD,DOLWRAD,LWSCAT,FLXLIMDIF,RAYSCAT,AEROSOLS,picket_fence_optical_depths,LRH,LNSURF

    NAMELIST/INCLOUDY/AEROSOLMODEL,AEROSOLCOMP,HAZETYPE,MTLX,METALLICITY,HAZES,PICKET_FENCE_CLOUDS,MOLEF,AERLAYERS,AERTOTTAU,CLOUDBASE,CLOUDTOP,AERHFRAC,PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,ASYMLW,DELTASCALE,SIG_AREA,PHI_LON
    NAMELIST/INPPL/GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT
    NAMELIST/COMMENT/THECOMMENT
    NAMELIST/INPRN/KRUN,BEGDAY,TSPD,KITS,PNU,TDISS,LFLUX,BEGDOY,NDEL,T0,LRSTRT,LSTRETCH,LSHORT,LTVEC,LBALAN,LRESTIJ,LCLIM,LPERPET,L22L,LOROG,LCSFCT,KOLOUR,LNOISE,LMASCOR,LMASOLD,LMASPRT
    !NAMELIST/INPOP/RNTAPE,KOUNTH,KOUNTR,KOUNTP,KOUNTE,NCOEFF,NLAT,LGPO,LSPO,RNTAPO,NTRACO,LSHIST,LMINIH
    NAMELIST/INVARPARAM/OOM_IN,LPLOTMAP,NLPLOTMAP_IN,RFCOEFF_IN,NTSTEP_IN,NSKIP_IN,BOTRELAXTIME,FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN
    NAMELIST/INMAG/LBDRAG,BFIELD,TDRAG_MIN,RAMPUP
    NAMELIST/INBINVAL/LBIN,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,STTEMP1,STTEMP2
    NAMELIST/INPHYS/LBL,LBD,LCR,LLR,LRD,LCUBM,LCBADJ,CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKTC,AKQC,NLCR,NCUTOP,FW,FRADC,CURHM,CUBMT,CBADJT,CBADJP,LSL,LOC,LNOICE,LOLDBL,LCOND,LNNSK,ITSLL,ITSLO
    NAMELIST/INPRSIJ/TFRC,RESTIM,RESTTT,REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN
    NAMELIST/INSIMPRAD/LLOGPLEV,LFLUXDIAG,L1DZENITH,LDIUR,JSKIPLON,JSKIPLAT,DOSWRAD,DOLWRAD,LWSCAT,FLXLIMDIF,SURFEMIS,RAYSCAT,RAYSCATLAM,AEROSOLS,ABSSW,ABSLW,ALBSW,NEWTB,NEWTE,with_TiO_and_VO,picket_fence_optical_depths
    NAMELIST/INQ/LRH,RH,LNSURF
    !so first test is below works, but then you can combine all above namelists to master namelist
    NAMELIST/REALS/MTLX, METALLICITY, MOLEF(13), AERTOTTAU, CLOUDTOP, AERHFRAC, PI0AERSW,ASYMSW,EXTFACTLW,PI0AERLW,ASYMLW, SIG_AREA, PHI_LON,GA,GASCON,RADEA,AKAP,WW,P0,RV,CLATNT,KRUN,BEGDAY,TSPD,PNU,TDISS,BEGDOY,RFCOEFF_IN,BOTRELAXTIME,FBASEFLUX,FORCE1DDAYS,OPACIR_POWERLAW,OPACIR_REFPRES,SOLC_IN,TOAALB,PORB,OBLIQ,ECCEN,BFIELD,TDRAG_MIN,RAMPUP,PORBST,ECCPL,ECCST,SMAPL,SMAST,STMASS1,STMASS2,STRAD1,STRAD2,CD,BLRH,AKVV,AKTV,AKQV,AKTC,AKQC,FW,FRADC,CURHM,CUBMT,CBADJT,TFRC,RESTIM, RESTTT(50),REDTEP,DTNS,DTEP,ALR,DTTRP,ZTROP,TGR,YRLEN,SURFEMIS,RAYSCATLAM(3),ABSSW,ABSLW,ALBSW,RH
    !i do not know how to change the read in path here, so instead I will move the fort.7 file over
    READ (7,INCLOUDY)
    !realarray(1) = INCLOUDY

    do i = 1, 79
        middlestep = tostring(REALS(i))
        TESTSTRING(i) = middlestep
    end do
    !write(*,'(a)')TESTSTRING

END SUBROUTINE testing1


