#!/bin/bash

####  Job name
#SBATCH --job-name=spectra

####  Request resources here
####  These are typically, number of processors, amount of memory,
####  an the amount of time a job requires.  May include processor
####  type, too.

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=7g
#SBATCH --time=36:00:00

#SBATCH --account=erausche1
#SBATCH --partition=standard

#### #### ####  These are the least frequently changing options

####  Your e-mail address and when you want e-mail

#SBATCH --mail-user=isaacmalsky@gmail.com
#SBATCH --mail-type=BEGIN,END,FAIL

module load gcc/10.3.0
module load python3.9

python run_entire_suite.py
